# [[file:~/Workspace/Programming/gosh-rs/optim/optim.note::*cargo][cargo:1]]
[package]
name = "gosh-optim"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
gosh-core = { version = ">=0.0.1", features=["adhoc"] }
gosh-model = { version = ">=0.0.11", features=["adhoc"] }
lbfgs = {version = "0.0.16", package="liblbfgs"}

[dev-dependencies]
# cargo:1 ends here
